---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - crd.yml
  - serviceaccount.yml
  - clusterrolebinding.yml
  - deployment.yml

images:
  - name: helm-controller
    newName: rancher/helm-controller
    newTag: "v0.17.6@sha256:5ded9ae9f543d3a027808083c0c2d9f3fe111eea1a70fb45625991fac77d6600"

...
