---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - crd.yml
  - serviceaccount.yml
  - clusterrolebinding.yml
  - deployment.yml

images:
  - name: helm-controller
    newName: rancher/helm-controller
    newTag: "v0.17.8@sha256:dc3b7498817ffedaf17930ecaed52838febceaaefa59181a851f9b79589ede4f"

...
