---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - crd.yml
  - serviceaccount.yml
  - clusterrolebinding.yml
  - deployment.yml

images:
  - name: helm-controller
    newName: rancher/helm-controller
    newTag: "v0.17.7@sha256:b8db825ff79a2474219db59c8c1b40113e6f2805eb88cef7437681c2640d3af4"

...
