---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: kustomize

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  kustomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Build manifest
        uses: actionhippie/kustomize@f7360f02e7d5c2f6fb509d55181c87fa32c23aba # v3
        with:
          print: true

...
