---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: linter

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Lint manifest
        uses: actionhippie/yamllint@42cde5141b45bc5832d61ed19007b5ca0f354753 # v1
        with:
          strict: true

...
